name: Deploy Workflows

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/resources/bpmn/*'

jobs:
  deploy-workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Updated Workflows
        uses: jwulf/zeebe-action@master
        #env: 
        #  ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
        with:
          client_config: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: deployWorkflow
          bpmn_directory: src/main/resources/bpmn
